import { useEffect, useMemo, useState } from 'react';
import './App.css';
const API = 'http://localhost:3000/api';

export default function App(){
  const [active,setActive]=useState('dashboard');
  const [tasks,setTasks]=useState([]); const [resources,setResources]=useState([]);
  const [name,setName]=useState(''); const [duration,setDuration]=useState(1);
  const [fromTask,setFromTask]=useState(''); const [toTask,setToTask]=useState('');
  const [resourceEmail,setResourceEmail]=useState(''); const [assignUser,setAssignUser]=useState(''); const [assignTask,setAssignTask]=useState(''); const [assignLoad,setAssignLoad]=useState(50);
  const [error,setError]=useState(''); const [success,setSuccess]=useState('');
  async function request(path, options={}){ const res = await fetch(`${API}${path}`, options); const ct=res.headers.get('content-type')||''; const data=ct.includes('json')?await res.json():await res.text(); if(!res.ok) throw new Error(data?.error||data||'Request fehlgeschlagen'); return data; }
  async function refresh(){ const [t,r]=await Promise.all([request('/tasks'), request('/resources').catch(()=>[])]); setTasks(Array.isArray(t)?t:[]); setResources(Array.isArray(r)?r:[]); }
  async function action(fn, ok){ try{ setError(''); setSuccess(''); await fn(); if(ok) setSuccess(ok); await refresh(); } catch(e){ setError(e.message); } }
  useEffect(()=>{ action(async()=>{}, ''); },[]); useEffect(()=>{ refresh().catch(e=>setError(e.message)); },[]);
  const createTask=()=>action(async()=>{ if(!name.trim()) throw new Error('Taskname fehlt'); await request('/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,duration:Number(duration)})}); setName(''); setDuration(1); },'Task erstellt');
  const schedule=()=>action(async()=>{ await request('/tasks/schedule',{method:'POST'}); },'Plan berechnet');
  const demo=()=>action(async()=>{ await request('/tasks/demo',{method:'POST'}); await request('/tasks/schedule',{method:'POST'}); },'Demo geladen');
  const clear=()=>action(async()=>{ await request('/tasks/demo',{method:'DELETE'}); },'Daten gelöscht');
  const dep=()=>action(async()=>{ if(!fromTask||!toTask) throw new Error('Von- und Zu-Task auswählen'); await request('/tasks/dependency',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fromId:Number(fromTask),toId:Number(toTask)})}); await request('/tasks/schedule',{method:'POST'}); setFromTask(''); setToTask(''); },'Dependency erstellt');
  const importFile=(e)=>action(async()=>{ const file=e.target.files?.[0]; if(!file) return; const fd=new FormData(); fd.append('file', file); await request('/tasks/import',{method:'POST',body:fd}); await request('/tasks/schedule',{method:'POST'}); e.target.value=''; },'Datei importiert');
  const createResource=()=>action(async()=>{ if(!resourceEmail.trim()) throw new Error('E-Mail fehlt'); await request('/resources',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:resourceEmail})}); setResourceEmail(''); },'Ressource erstellt');
  const assign=()=>action(async()=>{ if(!assignUser||!assignTask) throw new Error('Mitarbeiter und Task auswählen'); await request('/resources/assign',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:Number(assignUser),taskId:Number(assignTask),load:Number(assignLoad)})}); },'Zuweisung gespeichert');
  const stats = useMemo(()=>({ critical:tasks.filter(t=>t.critical).length, end:tasks.length?Math.max(...tasks.map(t=>t.end??0)):0, progress: tasks.length ? Math.round(tasks.filter(t=>t.status==='DONE').length/tasks.length*100) : 0 }),[tasks]);
  const ganttWidth=Math.max(650,(stats.end+2)*42);
  return <div className="app"><aside className="sidebar"><div className="logo">S</div><h2>Smenso</h2><p>Project Planning</p><nav>{['dashboard','tasks','gantt','resources','ai'].map(v=><button key={v} className={`nav-button ${active===v?'active':''}`} onClick={()=>setActive(v)}>{({dashboard:'Dashboard',tasks:'Tasks',gantt:'Gantt',resources:'Ressourcen',ai:'AI Planung'})[v]}</button>)}</nav></aside><main className="content"><header className="topbar"><div><h1>Projektplanung</h1><p>Tasks, Gantt, Import/Export und Ressourcenplanung</p></div><div className="actions"><button onClick={demo}>Demo laden</button><button className="danger" onClick={clear}>Löschen</button><button onClick={schedule}>Plan berechnen</button></div></header>{error&&<div className="error-box">{error}</div>}{success&&<div className="success-box">{success}</div>}<section className="stats"><Stat title="Tasks" value={tasks.length}/><Stat title="Fortschritt" value={`${stats.progress}%`}/><Stat title="Kritisch" value={stats.critical}/><Stat title="Projektende" value={`Tag ${stats.end}`}/></section>{(active==='dashboard'||active==='tasks')&&<section className="workspace"><TasksPanel tasks={tasks} name={name} setName={setName} duration={duration} setDuration={setDuration} createTask={createTask} fromTask={fromTask} setFromTask={setFromTask} toTask={toTask} setToTask={setToTask} dep={dep} importFile={importFile}/><Gantt tasks={tasks} width={ganttWidth}/><Resources resources={resources}/></section>}{active==='gantt'&&<section className="single"><Gantt tasks={tasks} width={ganttWidth} large/></section>}{active==='resources'&&<section className="single"><div className="panel"><h3>Ressourcen verwalten</h3><div className="row"><input placeholder="E-Mail" value={resourceEmail} onChange={e=>setResourceEmail(e.target.value)}/><button onClick={createResource}>Ressource anlegen</button></div><div className="row"><select value={assignUser} onChange={e=>setAssignUser(e.target.value)}><option value="">Mitarbeiter</option>{resources.map(r=><option key={r.id} value={r.id}>{r.email}</option>)}</select><select value={assignTask} onChange={e=>setAssignTask(e.target.value)}><option value="">Task</option>{tasks.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><input type="number" value={assignLoad} onChange={e=>setAssignLoad(e.target.value)}/><button onClick={assign}>Zuweisen</button></div><Resources resources={resources}/></div></section>}{active==='ai'&&<section className="single"><div className="panel"><h3>AI Planung</h3><p className="muted">AI-Endpunkte sind vorbereitet.</p></div></section>}</main></div>
}
function Stat({title,value}){ return <div className="stat"><span>{title}</span><strong>{value}</strong></div> }
function TasksPanel(p){ return <div className="panel"><h3>Tasks</h3><div className="task-form"><input placeholder="Taskname" value={p.name} onChange={e=>p.setName(e.target.value)}/><input type="number" min="1" value={p.duration} onChange={e=>p.setDuration(e.target.value)}/><button onClick={p.createTask}>Add</button></div><div className="dependency-box"><select value={p.fromTask} onChange={e=>p.setFromTask(e.target.value)}><option value="">Von Task</option>{p.tasks.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select value={p.toTask} onChange={e=>p.setToTask(e.target.value)}><option value="">Zu Task</option>{p.tasks.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button onClick={p.dep}>Verbinden</button></div><div className="import-export"><input type="file" accept=".csv,.xlsx" onChange={p.importFile}/><button onClick={()=>window.open(`${API}/tasks/export/csv`)}>CSV Export</button><button onClick={()=>window.open(`${API}/tasks/export/excel`)}>Excel Export</button><button onClick={()=>window.open(`${API}/tasks/export/pdf`)}>PDF Export</button></div><div className="task-list">{p.tasks.length? p.tasks.map(t=><div key={t.id} className="task-item"><div><strong>{t.name}</strong><small>{t.phase||'Keine Phase'}</small></div><span>{t.start??'-'} → {t.end??'-'}</span>{t.critical&&<b className="critical">●</b>}</div>) : <p className="muted">Keine Tasks vorhanden</p>}</div></div> }
function Gantt({tasks,width,large}){ return <div className={`panel gantt-panel ${large?'large':''}`}><h3>Gantt Chart</h3><div className="gantt-scroll"><div className="gantt" style={{width}}><div className="axis">{Array.from({length: Math.max(1, Math.ceil(width/42))},(_,i)=><span key={i}>T{i}</span>)}</div>{tasks.map(t=><div key={t.id} className="gantt-row"><div className="gantt-label">{t.name}</div><div className="track"><div className={`bar ${t.critical?'critical-bar':''}`} style={{left:(t.start??0)*42, width:Math.max(32,(t.duration||1)*42)}}>{t.duration}d</div></div></div>)}</div></div></div> }
function Resources({resources}){ return <div className="panel"><h3>Ressourcen</h3>{resources.length?resources.map(r=><div key={r.id} className={`resource-card ${r.totalLoad>100?'overload':''}`}><strong>{r.email}</strong><span>{r.totalLoad||0}% Auslastung</span></div>):<p className="muted">Keine Ressourcen vorhanden</p>}</div> }
